services:
  redis:
    image: redis:7
    container_name: locco-redis
    ports:
      - "6380:6379"
  mongodb:
    image: mongo:7
    container_name: locco-mongodb
    ports:
      - "27018:27017"
  postgres:
    image: postgres:17
    container_name: locco-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
